### ISSUE TITLE
Invalid value for "v" parameter: cannot convert "" to number;

### ISSUE THREAD

**Issue by sadok-f** [Invicton-Labs/terraform-external-shell-resource#14]
Hello there,

I'm facing an issue with the module, which throws a the following error:
```sh
│ Error: Invalid function argument
│ 
│   on .terraform/modules/xxxx-external-shell-resourc/outputs.tf line 98, in output "exit_code":
│   98:   value       = local.outputs.exit_code == null ? null : tonumber(local.outputs.exit_code)
│     ├────────────────
│     │ while calling tonumber(v)
│     │ local.outputs.exit_code is ""
│ 
│ Invalid value for "v" parameter: cannot convert "" to number; given string
│ must be a decimal representation of a number.
```

I think the issue is coming from the line https://github.com/Invicton-Labs/terraform-external-shell-resource/blob/main/main.tf#L346
```hcl
xitcode     = !local.create_command_exists ? 0 : local.exitcode_str == "" ? "" : local.exitcode_str == "null" ? null : tonumber(local.exitcode_str)
```
Where it checks if the `local.exitcode_str` is an empty string and returns an empty string, but later on the `outputs.tf` file https://github.com/Invicton-Labs/terraform-external-shell-resource/blob/main/outputs.tf#L98  it runs a `tonumber(local.outputs.exit_code)` which throw an error when the value is empty

I'll create a PR to remove the `tonumber` function in the outputs.tf since you already doing that.

Thank you

**Comment by sadok-f** [comment]
Hi @KyleKotowick , could you please review this issue and the PR related to it?
its kinda of a blocking point for us.
thank you

**Comment by KyleKotowick** [comment]
@sadok-f Could you provide a minimum example of a Terraform config that shows this error, so I can reproduce it?

**Comment by sadok-f** [comment]
@KyleKotowick thank you for your response, it's a bit tricky since `terraform-external-shell-resource` module is used by another module which calls an API with python with tons of parameters.
but my point is in line  https://github.com/Invicton-Labs/terraform-external-shell-resource/blob/main/main.tf#L346
you're checking for the `exitcode_str == "" ` then return `""` , in output.tf you should remove the `tonumber` otherwise the exitcode returns an empty string and then the error `Invalid value for "v" parameter: cannot convert "" to number` will showup

so maybe using the module `terraform-external-shell-resource` that calls a bash script returning "" will reproduce the issue

**Comment by sadok-f** [comment]
Hey @KyleKotowick,
Here is an example of the tfstate for the failed module:
```
 {
      "module": "module.my-module",
      "mode": "managed",
      "type": "random_id",
      "name": "outputs",
      "provider": "provider[\"registry.terraform.io/hashicorp/random\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "b64_std": "eyJleGl0X2NvZGUiOiIiLCJzdGRlcnIiOiIiLCJzdGRvdXQiOiIifQ==|YA==",
            "b64_url": "eyJleGl0X2NvZGUiOiIiLCJzdGRlcnIiOiIiLCJzdGRvdXQiOiIifQ==|YA",
            "byte_length": 1,
            "dec": "eyJleGl0X2NvZGUiOiIiLCJzdGRlcnIiOiIiLCJzdGRvdXQiOiIifQ==|96",
            "hex": "eyJleGl0X2NvZGUiOiIiLCJzdGRlcnIiOiIiLCJzdGRvdXQiOiIifQ==|60",
            "id": "YA",
            "keepers": {
              "command_create_filename_windows": "2c74de3b-9fab-cadf-2be4-fae89de926c5.create.ps1",
              "command_create_unix": "8fdf90ecf357c86d3a88c1210dca8d725677417b29ae8e3df997e71e43a8956f",
              "command_create_windows": "1a3b4497a0eb129d2a347b554286a10e2c004e398c37977d5cb2d8439be9b0fa",
              "command_destroy_filename_windows": "2c74de3b-9fab-cadf-2be4-fae89de926c5.destroy.ps1",
              "command_destroy_unix": "/bin/bash -c 'pip3 install -r requirements.txt --quiet && python3 script.py",
              "command_destroy_windows": "",
              "env_var_file_create": "2c74de3b-9fab-cadf-2be4-fae89de926c5.create.env",
              "env_var_file_destroy": "2c74de3b-9fab-cadf-2be4-fae89de926c5.destroy.env",
              "environment": "xxxx",
              "environment_sensitive": "xxxx",
              "execution_id": "2c74de3b-9fab-cadf-2be4-fae89de926c5",
              "exitcode_file": "2c74de3b-9fab-cadf-2be4-fae89de926c5.exitcode",
              "fail_create_on_nonzero_exit_code": "true",
              "fail_create_on_stderr": "false",
              "fail_create_on_timeout": "true",
              "fail_destroy_on_nonzero_exit_code": "true",
              "fail_destroy_on_stderr": "false",
              "fail_destroy_on_timeout": "true",
              "is_debug": "false",
              "null_command_unix": ":",
              "null_command_windows": "% ':'",
              "stderr_file": "2c74de3b-9fab-cadf-2be4-fae89de926c5.stderr",
              "stdout_file": "2c74de3b-9fab-cadf-2be4-fae89de926c5.stdout",
              "temp_dir": "tmpfiles",
              "timeout_create": "0",
              "timeout_destroy": "0",
              "triggers": "{}",
              "unix_interpreter": "/bin/sh",
              "windows_file_input_create_required": "false",
              "windows_file_input_destroy_required": "false",
              "working_dir": "."
            },
            "prefix": "eyJleGl0X2NvZGUiOiIiLCJzdGRlcnIiOiIiLCJzdGRvdXQiOiIifQ==|"
          },
```
as you can see the value of `b64_std` decoded is `{"exit_code":"","stderr":"","stdout":""}` and there the `exit_code` is `""`
it seems the issue happened during pip3 install command where it failed and threw this error:
```
exit status 1. Output: ERROR: Could not install packages due to an OSError:
│ [Errno 2] No such file or directory:
│ '/usr/lib/python3.11/site-packages/yaml/reader.py'
```
from that moment any `terraform apply` or `terraform plan` in our pipeline is failing with the error:
```
│ Error: Invalid function argument
│
│   on .terraform/modules/my-module/outputs.tf line 98, in output "exit_code":
│   98:   value       = local.outputs.exit_code == null ? null : tonumber(local.outputs.exit_code)
│     ├────────────────
│     │ while calling tonumber(v)
│     │ local.outputs.exit_code is ""
│
│ Invalid value for "v" parameter: cannot convert "" to number; given string must be a decimal representation of a number.

```

I did reproduce the issue locally by removing manually the file `site-packages/yaml/reader.py` and the fix was to remove  `tonumber ` from 
https://github.com/Invicton-Labs/terraform-external-shell-resource/blob/main/outputs.tf#L98

I hope I give enough explanation about the issue, please let me know if you need any more details

Thanks

**Comment by KyleKotowick** [comment]
The issue here is that it should never be able to get to this state. Was this a situation where you already had this module in the state file, then upgraded the module version to a new version? In `v0.X.Y`, changes to `Y` are backwards-compatible, while changes to `X` are not, and usually require a taint/recreate.

The value of `local.exitcode_content`, which is the first source of the exit code, should only be an empty string if the exitcode output file doesn't exist. The exitcode outfile should always exist if the resource is being created on a given `terraform apply`, and therefore it should never be an empty string during a `terraform apply` where the resource is created.

The `random_id` resource only stores the exitcode in the prefix string if the triggers are changed, and those triggers are the same as the shell resource triggers, so the `random_id` should never be triggered to recreate while there's an empty string in the exitcode value. Therefore, only real exit codes should be stored in the `random_id` prefix when the triggers are changed; it should never be an empty string.

So the issue with your state file is that there should never be `{"exit_code": "" ...}` in the `b64_std` value. _That's_ the problem here, not there `tonumber` on the output. The `tonumber` should be fine, since in no case should that output ever get an empty string.

I think the incompatible version update is the most likely explanation, so try tainting and re-creating this shell resource if you can (it's best practice to make these things idempotent anyways, in case a recreate is unintentionally triggered for whatever reason). If it still fails after that, you'll need to send me a minimum example of what the issue is. I can't/won't merge the PR, because it would allow the output exitcode to be an empty string, which it should never be (and other users are likely relying on that output to be a `number` and not a `string`).

Unrelated, but I'm quite curious as to why you're doing a `pip install` when the resource is destroyed (`command_destroy_unix` in your state file). Seems like you'd want a `pip uninstall` instead.

**Comment by sadok-f** [comment]
The issue happened on a gitlab pipeline for a production system, it seems the gitlab runners where the job is executing got crashed and the `exit_code` got an empty string.
we had to delete manually the state of the failed object (via `terraform state rm ...`) and rerun the job again to overcome the issue.
it happened to us, it could happen to anyone else who using this module.

if you're saying the exitcode should never be an empty string, then why in your code you're checking if `exitcode_st`r gets an empty string and return back an empty string? in that case you could just return 0 and the issue will be solved.
here in the line 346 in main.tf
https://github.com/Invicton-Labs/terraform-external-shell-resource/blob/main/main.tf#L346
```hcl
exitcode     = !local.create_command_exists ? 0 : local.exitcode_str == "" ? "" : local.exitcode_str == "null" ? null : tonumber(local.exitcode_str)
```
if ` local.exitcode_str == "" ` then return `""` and the in the outputs.tf ` tonumber(local.outputs.exit_code)` won't work because you're returning an empty string.

I know this is probably an edge case where the `exitcode` gets an empty string, but even with that the module should handle that properly.

Regarding the `command_destroy_unix` it's intendant to install some libs and then use them in the python script to destroy resources.

I hope you get my point here, thanks.

**Comment by KyleKotowick** [comment]
If the script fails and outputs an empty string for the exit code, we can't just default it to `0` instead because `0` indicates there was no issue, and clearly there was an issue.

The preferred approach would be to catch that eventuality (script crashes and doesn't output anything) and throw a custom error message, but TF doesn't really support any way to do that, as it would require (a) detecting the empty string response, AND (b) knowing whether the resource was newly created, or if it already existed.

**Comment by sadok-f** [comment]
We inherited the terraform module from some vendors, which uses `terraform-external-shell-resource` underline it, which calls a Saas provider API in python to manage some resources, I know this shouldn't be the case of using this module in the first place, but until we get an official terraform provider we have to live with it.

I updated the PR to change when `local.exitcode_str == ""` then return `null` instead of empty strings which cause the error in `tonumber` function.

I can update it to return `1` if you want, the main point here is that if it returns an empty string `""` then the module crashes with the following error:
```sh
│ Error: Invalid function argument
│ 
│   on .terraform/modules/shell-module/outputs.tf line 98, in output "exit_code":
│   98:   value       = local.outputs.exit_code == null ? null : tonumber(local.outputs.exit_code)
│     ├────────────────
│     │ while calling tonumber(v)
│     │ local.outputs.exit_code is ""
│ 
│ Invalid value for "v" parameter: cannot convert "" to number; given string
│ must be a decimal representation of a number.
```

**Comment by KyleKotowick** [comment]
I'm sorry, but I can't approve a PR for a workaround for a scenario that, logically, should never exist (and apparently only exists due to the runner crashing during the `apply`). That's a one-off scenario that needs to be fixed manually. My recommendation is to manually edit the state file to fix this, or to update the script that you're running to be idempotent and simply `terraform state rm` to remove this module, then let it be re-created cleanly.

**Comment by sadok-f** [comment]
I don't agree with you, this is not a workaround, you have a bug in the code and there's an edge case that triggers it.
put aside the scenario that this error occurred with, you're returning an empty string and then doing `tonumber` to it? this obviously a bug and it needs to be fixed since it happened to me it could happen to anyone else using the project.
I'm going to use my forked version of the module to overcome the error,  this shouldn't be the way how to run an open-source project.
Thanks anyway.

**Comment by joaocc** [comment]
Any updates on this? We started encountering this recently on some executions (ie, same code, different servers). Without a fix we cannot use the module, as the check is done inside the module.

**Comment by sadok-f** [comment]
bingo!
@joaocc I ended up using my forked version which fixed this issue:
https://github.com/sadok-f/terraform-external-shell-resource
